version: '3'
services:
  rmd-light_4.1.2:
    image: mattocci/rmd-light:4.1.2
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140:82:114:4
    build:
      context: .
      dockerfile: images/rmd-light_4.1.2/Dockerfile
  rstan_4.1.2:
    image: mattocci/rstan:4.1.2
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140:82:114:4
    build:
      context: .
      dockerfile: images/rstan_4.1.2/Dockerfile
  myenv_4.1.2:
    image: mattocci/myenv:4.1.2
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140:82:114:4
    build:
      context: .
      dockerfile: images/myenv_4.1.2/Dockerfile
  cmdstanr_4.1.2:
    image: mattocci/cmdstanr:4.1.2
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140:82:114:4
    build:
      context: .
      dockerfile: images/cmdstanr_4.1.2/Dockerfile
