version: '3'
services:
  radian_4.4.2_arm64:
    image: mattocci/radian:4.4.2_arm64
    build:
      context: .
      dockerfile: images/radian_4.4.2_arm64/Dockerfile
  radian-verse_4.4.2_arm64:
    image: mattocci/radian-verse:4.4.2_arm64
    build:
      context: .
      dockerfile: images/radian-verse_4.4.2_arm64/Dockerfile
  cmdstan-verse_4.4.2_arm64:
    image: mattocci/cmdstan-verse:4.4.2_arm64
    build:
      context: .
      dockerfile: images/cmdstan-verse_4.4.2_arm64/Dockerfile
  cmdstan-verse-zsh_4.4.2_arm64:
    image: mattocci/cmdstan-verse-zsh:4.4.2_arm64
    build:
      context: .
      dockerfile: images/cmdstan-verse-zsh_4.4.2_arm64/Dockerfile
  radian_4.4.2_amd64:
    image: mattocci/radian:4.4.2_amd64
    build:
      context: .
      dockerfile: images/radian_4.4.2_amd64/Dockerfile
  radian-verse_4.4.2_amd64:
    image: mattocci/radian-verse:4.4.2_amd64
    build:
      context: .
      dockerfile: images/radian-verse_4.4.2_amd64/Dockerfile
  cmdstan-verse_4.4.2_amd64:
    image: mattocci/cmdstan-verse:4.4.2_amd64
    build:
      context: .
      dockerfile: images/cmdstan-verse_4.4.2_amd64/Dockerfile
  cmdstan-verse-zsh_4.4.2_amd64:
    image: mattocci/cmdstan-verse-zsh:4.4.2_amd64
    build:
      context: .
      dockerfile: images/cmdstan-verse-zsh_4.4.2_amd64/Dockerfile
