version: '3'
services:
  tinytex_4.3.0:
    image: mattocci/tinytex:4.3.0
    build:
      context: .
      dockerfile: images/tinytex_4.3.0/Dockerfile
  radian_4.3.0:
    image: mattocci/radian:4.3.0
    build:
      context: .
      dockerfile: images/radian_4.3.0/Dockerfile
  radian-verse_4.3.0:
    image: mattocci/radian-verse:4.3.0
    build:
      context: .
      dockerfile: images/radian-verse_4.3.0/Dockerfile
  radian-ml_4.3.0:
    image: mattocci/radian-ml:4.3.0
    build:
      context: .
      dockerfile: images/radian-ml_4.3.0/Dockerfile
  rstan_4.3.0:
    image: mattocci/rstan:4.3.0
    build:
      context: .
      dockerfile: images/rstan_4.3.0/Dockerfile
  cmdstanr_4.3.0:
    image: mattocci/cmdstanr:4.3.0
    build:
      context: .
      dockerfile: images/cmdstanr_4.3.0/Dockerfile
