version: '3'
services:
  radian_4.3.3:
    image: mattocci/radian:4.3.3
    build:
      context: .
      dockerfile: images/radian_4.3.3/Dockerfile
  radian-verse_4.3.3:
    image: mattocci/radian-verse:4.3.3
    build:
      context: .
      dockerfile: images/radian-verse_4.3.3/Dockerfile
  cmdstan-verse_4.3.3:
    image: mattocci/cmdstan-verse:4.3.3
    build:
      context: .
      dockerfile: images/cmdstan-verse_4.3.3/Dockerfile
  cmdstan-verse-zsh_4.3.3:
    image: mattocci/cmdstan-verse-zsh:4.3.3
    build:
      context: .
      dockerfile: images/cmdstan-verse-zsh_4.3.3/Dockerfile
