version: '3'
services:
  radian_4.2.1:
    image: mattocci/radian:4.2.1
    build:
      context: .
      dockerfile: images/radian_4.2.1/Dockerfile
  radian-verse_4.2.1:
    image: mattocci/radian-verse:4.2.1
    build:
      context: .
      dockerfile: images/radian-verse_4.2.1/Dockerfile
  cmdstan-verse_4.2.1:
    image: mattocci/cmdstan-verse:4.2.1
    build:
      context: .
      dockerfile: images/cmdstan-verse_4.2.1/Dockerfile
  cmdstan-verse-zsh_4.2.1:
    image: mattocci/cmdstan-verse-zsh:4.2.1
    build:
      context: .
      dockerfile: images/cmdstan-verse-zsh_4.2.1/Dockerfile
