version: '3'
services:
  tinytex_4.1.3:
    image: mattocci/tinytex:4.1.3
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/tinytex_4.1.3/Dockerfile
  radian_4.1.3:
    image: mattocci/radian:4.1.3
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/radian_4.1.3/Dockerfile
