version: '3'
services:
  tinytex_4.2.1:
    image: mattocci/tinytex:4.2.1
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/tinytex_4.2.1/Dockerfile
  radian_4.2.1:
    image: mattocci/radian:4.2.1
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/radian_4.2.1/Dockerfile
  radian-ml_4.2.1:
    image: mattocci/radian-ml:4.2.1
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/radian-ml_4.2.1/Dockerfile
  rstan_4.2.1:
    image: mattocci/rstan:4.2.1
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/rstan_4.2.1/Dockerfile
  cmdstanr_4.2.1:
    image: mattocci/cmdstanr:4.2.1
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/cmdstanr_4.2.1/Dockerfile
