version: '3'
services:
  rmd-light_4.1.3:
    image: mattocci/rmd-light:4.1.3
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/rmd-light_4.1.3/Dockerfile
  rstan_4.1.3:
    image: mattocci/rstan:4.1.3
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/rstan_4.1.3/Dockerfile
  myenv_4.1.3:
    image: mattocci/myenv:4.1.3
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/myenv_4.1.3/Dockerfile
  cmdstanr_4.1.3:
    image: mattocci/cmdstanr:4.1.3
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/cmdstanr_4.1.3/Dockerfile
  myenv-light_4.1.3:
    image: mattocci/myenv-light:4.1.3
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/myenv-light_4.1.3/Dockerfile
  radian_4.1.3:
    image: mattocci/radian:4.1.3
    extra_hosts:
    - api.github.com:140.82.113.6
    - github.com:140.82.114.4
    build:
      context: .
      dockerfile: images/radian_4.1.3/Dockerfile
