version: '3'
services:
  tinytex_4.3.2:
    image: mattocci/tinytex:4.3.2
    build:
      context: .
      dockerfile: images/tinytex_4.3.2/Dockerfile
  radian_4.3.2:
    image: mattocci/radian:4.3.2
    build:
      context: .
      dockerfile: images/radian_4.3.2/Dockerfile
  radian-verse_4.3.2:
    image: mattocci/radian-verse:4.3.2
    build:
      context: .
      dockerfile: images/radian-verse_4.3.2/Dockerfile
  cmdstan-verse_4.3.2:
    image: mattocci/cmdstan-verse:4.3.2
    build:
      context: .
      dockerfile: images/cmdstan-verse_4.3.2/Dockerfile
  rstan_4.3.2:
    image: mattocci/rstan:4.3.2
    build:
      context: .
      dockerfile: images/rstan_4.3.2/Dockerfile
