version: '3'
services:
  cmdstan_4.1.1:
    image: mattocci/cmdstan:4.1.1
    extra_hosts:
    - api.github.com:140.82.113.6
    build:
      context: .
      dockerfile: images/cmdstan_4.1.1/Dockerfile
  rstan_4.1.1:
    image: mattocci/rstan:4.1.1
    extra_hosts:
    - api.github.com:140.82.113.6
    build:
      context: .
      dockerfile: images/rstan_4.1.1/Dockerfile
  myenv_4.1.1:
    image: mattocci/myenv:4.1.1
    extra_hosts:
    - api.github.com:140.82.113.6
    build:
      context: .
      dockerfile: images/myenv_4.1.1/Dockerfile
  rmd-light_4.1.1:
    image: mattocci/rmd-light:4.1.1
    extra_hosts:
    - api.github.com:140.82.113.6
    build:
      context: .
      dockerfile: images/rmd-light_4.1.1/Dockerfile
