version: '3'
services:
  radian_4.5.1_arm64:
    image: mattocci/radian:4.5.1_arm64
    build:
      context: .
      dockerfile: images/radian_4.5.1_arm64/Dockerfile
  radian-verse_4.5.1_arm64:
    image: mattocci/radian-verse:4.5.1_arm64
    build:
      context: .
      dockerfile: images/radian-verse_4.5.1_arm64/Dockerfile
  radian-claude_4.5.1_arm64:
    image: mattocci/radian-claude:4.5.1_arm64
    build:
      context: .
      dockerfile: images/radian-claude_4.5.1_arm64/Dockerfile
  cmdstan-verse_4.5.1_arm64:
    image: mattocci/cmdstan-verse:4.5.1_arm64
    build:
      context: .
      dockerfile: images/cmdstan-verse_4.5.1_arm64/Dockerfile
  cmdstan-zsh_4.5.1_arm64:
    image: mattocci/cmdstan-zsh:4.5.1_arm64
    build:
      context: .
      dockerfile: images/cmdstan-zsh_4.5.1_arm64/Dockerfile
  cmdstan-claude_4.5.1_arm64:
    image: mattocci/cmdstan-claude:4.5.1_arm64
    build:
      context: .
      dockerfile: images/cmdstan-claude_4.5.1_arm64/Dockerfile
  radian_4.5.1_amd64:
    image: mattocci/radian:4.5.1_amd64
    build:
      context: .
      dockerfile: images/radian_4.5.1_amd64/Dockerfile
  radian-verse_4.5.1_amd64:
    image: mattocci/radian-verse:4.5.1_amd64
    build:
      context: .
      dockerfile: images/radian-verse_4.5.1_amd64/Dockerfile
  radian-claude_4.5.1_amd64:
    image: mattocci/radian-claude:4.5.1_amd64
    build:
      context: .
      dockerfile: images/radian-claude_4.5.1_amd64/Dockerfile
  cmdstan-verse_4.5.1_amd64:
    image: mattocci/cmdstan-verse:4.5.1_amd64
    build:
      context: .
      dockerfile: images/cmdstan-verse_4.5.1_amd64/Dockerfile
  cmdstan-zsh_4.5.1_amd64:
    image: mattocci/cmdstan-zsh:4.5.1_amd64
    build:
      context: .
      dockerfile: images/cmdstan-zsh_4.5.1_amd64/Dockerfile
  cmdstan-claude_4.5.1_amd64:
    image: mattocci/cmdstan-claude:4.5.1_amd64
    build:
      context: .
      dockerfile: images/cmdstan-claude_4.5.1_amd64/Dockerfile
