# {{ note }}
FROM {{ baseImage }}

{% if label %}
LABEL {{ label | join('\ ') }}
{% endif %}

ENV DEBIAN_FRONTEND noninteractive

{% if systemPackages %}
RUN apt-get update -q -y \
  && apt-get install --no-install-recommends --fix-missing -y \
    {% for package in systemPackages %}
    {{ package }} \
    {% endfor %}
  && apt-get autoremove -y \
  && apt-get clean all
{% endif %}

{% if crossref %}
RUN rm -rf /usr/lib/rstudio-server/bin/pandoc/pandoc \
  usr/local/bin/pandoc \
  usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc \
  usr/local/bin/pandoc-citeproc 

RUN PANDOC_DL_URL=$(wget -qO- https://api.github.com/repos/jgm/pandoc/releases/latest | grep -oP "(?<=\"browser_download_url\":\s\")https.*amd64.deb") \
  && wget ${PANDOC_DL_URL} -O pandoc-amd64.deb \
  && dpkg -i pandoc-amd64.deb \
  && rm pandoc-amd64.deb

## Symlink pandoc & standard pandoc templates for use system-wide
RUN PANDOC_TEMPLATES_VERSION=`pandoc -v | grep -oP "(?<=pandoc\s)[0-9\.]+$"` \
 && wget https://github.com/jgm/pandoc-templates/archive/${PANDOC_TEMPLATES_VERSION}.tar.gz -O pandoc-templates.tar.gz \
 && rm -fr /opt/pandoc/templates \
 && mkdir -p /opt/pandoc/templates \
 && tar xvf pandoc-templates.tar.gz \
 && cp -r pandoc-templates*/* /opt/pandoc/templates && rm -rf pandoc-templates* \
 && rm -fr /root/.pandoc \
 && mkdir /root/.pandoc && ln -s /opt/pandoc/templates /root/.pandoc/templates

RUN CROSSREF_DL_URL=$(wget -qO- https://api.github.com/repos/lierdakil/pandoc-crossref/releases/latest | grep -oP "(?<=\"browser_download_url\":\s\")https.*tar\.xz" | grep Linux) \
  && wget -O - ${CROSSREF_DL_URL} | \
  tar Jxf - \
  && mv pandoc-crossref /usr/local/bin \
  && rm -rf pandoc-crossref.1
{% endif %}

{% if radian %}
RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
  && pip3 install --upgrade setuptools \
  && pip3 install --default-timeout=100 -U radian
{% endif %}

{% if bio %}
RUN Rscript -e "install.packages('BiocManager')" \
  && Rscript -e "BiocManager::install(c('marray', 'affy', 'Biobase'))"
{% endif %}

{% if installGithub %}
RUN installGithub.r \
  {{ installGithub | join('\ ') }}
{% endif %}

{% if installCRAN %}
RUN install2.r -n -1 --skipinstalled --error \
  --deps TRUE \
    {% for cran in installCRAN %}
    {{ cran }} \
    {% endfor %}
  && rm -rf /tmp/downloaded_packages
{% endif %}
