name: Multibuild

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker images
        run: |

          docker pull mattocci/radian:4.4.2_amd64
          docker pull mattocci/radian:4.4.2_arm64

          docker manifest create mattocci/radian:4.4.2 \
            mattocci/radian:4.4.2_amd64 \
            mattocci/radian:4.4.2_arm64

          docker manifest push mattocci/radian:4.4.2
