name: Multibuild

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker images
        run: |
          set -e
          images=("radian" "radian-verse" "cmdstan-verse" "cmdstan-verse-zsh")
          for image in "${images[@]}"; do
            echo "Processing image: $image"

            # Pull images with explicit platform flags
            docker pull --platform linux/amd64 mattocci/${image}:4.4.3_amd64
            docker pull --platform linux/arm64 mattocci/${image}:4.4.3_arm64

            # Extract digests for both architectures using --format for valid JSON output
            amd64_digest=$(docker buildx imagetools inspect --format '{{json .}}' mattocci/${image}:4.4.3_amd64 | \
              jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')
            arm64_digest=$(docker buildx imagetools inspect --format '{{json .}}' mattocci/${image}:4.4.3_arm64 | \
              jq -r '.manifests[] | select(.platform.architecture=="arm64") | .digest')

            echo "AMD64 digest for $image: ${amd64_digest}"
            echo "ARM64 digest for $image: ${arm64_digest}"

            # Remove any existing manifest list (ignore errors)
            docker manifest rm mattocci/${image}:4.4.3 || true

            # Create the multi-arch manifest list using the extracted digests
            docker manifest create mattocci/${image}:4.4.3 \
              "mattocci/${image}@${amd64_digest}" \
              "mattocci/${image}@${arm64_digest}"

            # Push the manifest list
            docker manifest push mattocci/${image}:4.4.3
          done
