Can you make this workflow more efficient and/or cleaner?
name: Multibuild

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker images
        run: |
          docker pull mattocci/radian:4.4.2_amd64
          docker pull mattocci/radian:4.4.2_arm64

          radian_amd64_digest=$(docker manifest inspect mattocci/radian:4.4.2_amd64 | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')

          docker manifest create mattocci/radian:4.4.2 \
            "mattocci/radian@${radian_amd64_digest}" \
            mattocci/radian:4.4.2_arm64

          docker manifest push mattocci/radian:4.4.2

          docker pull mattocci/radian_verse:4.4.2_amd64
          docker pull mattocci/radian_verse:4.4.2_arm64

          radian_verse_amd64_digest=$(docker manifest inspect mattocci/radian_verse:4.4.2_amd64 | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')

          docker manifest create mattocci/radian_verse:4.4.2 \
            "mattocci/radian_verse@${radian_verse_amd64_digest}" \
            mattocci/radian_verse:4.4.2_arm64

          docker manifest push mattocci/cmdstan_verse:4.4.2

          docker pull mattocci/cmdstan:4.4.2_amd64
          docker pull mattocci/cmdstan:4.4.2_arm64

          cmdstan_amd64_digest=$(docker manifest inspect mattocci/cmdstan:4.4.2_amd64 | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')

          docker manifest create mattocci/cmdstan:4.4.2 \
            "mattocci/cmdstan@${cmdstan_amd64_digest}" \
            mattocci/cmdstan:4.4.2_arm64

          docker manifest push mattocci/cmdstan:4.4.2

          docker pull mattocci/cmdstan_verse_zsh:4.4.2_amd64
          docker pull mattocci/cmdstan_verse_zsh:4.4.2_arm64

          cmdstan_verse_zsh_amd64_digest=$(docker manifest inspect mattocci/cmdstan_verse_zsh:4.4.2_amd64 | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')

          docker manifest create mattocci/cmdstan_verse_zsh:4.4.2 \
            "mattocci/cmdstan_verse_zsh@${cmdstan_verse_zsh_amd64_digest}" \
            mattocci/cmdstan_verse_zsh:4.4.2_arm64

          docker manifest push mattocci/cmdstan_verse_zsh:4.4.2
