name: Build and push

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    paths:
      - 'images/**'
      - '**.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - uses: Gr1N/setup-poetry@v9

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{runner.os}}-poetry-${{hashFiles('**/poetry.lock')}}
          restore-keys: |
            ${{runner.os}}-poetry-

      - run: |
          poetry --version
          poetry install
          poetry run python scripts/update.py
          poetry run python scripts/generate_yml.py

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push radian_4.3.2 for arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/radian_4.3.2/Dockerfile
          push: true
          platforms: linux/arm64
          tags: mattocci/radian:4.3.2

      - name: Build and push radian-verse_4.3.2 for arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/radian-verse_4.3.2/Dockerfile
          push: true
          platforms: linux/arm64
          tags: mattocci/radian-verse:4.3.2

      - name: Build and push cmdstan-verse_4.3.2 for arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/cmdstan-verse_4.3.2/Dockerfile
          push: true
          platforms: linux/arm64
          tags: mattocci/cmdstan-verse:4.3.2

      - name: Build and push cmdstan-verse-zsh_4.3.2 for arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/cmdstan-verse-zsh_4.3.2/Dockerfile
          push: true
          platforms: linux/arm64
          tags: mattocci/cmdstan-verse-zsh:4.3.2

